sudo: required
services: docker
language: python
python: '3.6'
before_install:
- sudo apt-get update
- sudo apt-get -y -o Dpkg::Options::="--force-confnew" install docker-ce
install:
- pip install -r tests/requirements.txt
- docker plugin install rasmunk/sshfs --grant-all-permissions
script:
- python setup.py check -rms
- flake8
- travis_wait pytest -s -v tests/
deploy:
  skip_cleanup: true
  distributions: sdist bdist_wheel
  provider: pypi
  user: rasmunk
  password:
    secure: mVjwAPA2gRQ7fhsNrz6bEoouj7rGg9WcLUzDxiYNWsAySiAcbbIET+gCkf6ZtDYHcm7k45VedRPXP2xut1cqr95D6LMtELETotqfgYWiaQwl4dbMDJQym0qLmEqCG0rxkX+IxnsyLZafVnqPtSm2lnQBneBwyOj2Td4FDNfv+QABC/ZZlXP8ahKb73UdZhfbpAxJza9D8vbyNV6qLBLv3oppOHUhdnXo3GcQ9dMs0mEjydEcGfxc3PY7oqrl3Kktrepu9tipbWtm0V4H5tKamZ774J/ov+xrqY0a8CCxNv7XWfh9jFeowjqHBExqyBBl9R40mVcxfC+bwbXN5j7a3Y4ZRp38rYzpnS+RMJHBGBAeBwrikRceuqwMRivCChiTHNA3jv8S2HxBuihYC/ldORvmXyFN7/qbUq5LLReG4NUK8SoZsfSRTdgncMJkD/hBQUPHVnXLxbKO430hcTb1LAgE61ywEyJJWyGlfdHkbULNWhWRNi2CJtufETo+fS95SoEPWlzgK8nBkXm1EQgqf01ZZ9uLDia699ozkXiqahlYt4DZuGehQcTWwSSjofR2OS9nOtUdO7a4/G4zQTf+DbHeDxIVmlJpKuxcXp3pQOoeH5PKpKR6Un6TP0QMVcvpP4dqCKhmLl+sJ9yKH6O54TMukvWt8+DTAwcjbSiSDIo=
  on:
    tags: true
    branch: master
notifications: 
  slack: raz-s:se1PurXsQJv03nBZa9XWMOOS